### PR TITLE
[UI part]: enable c++20

### PR DESCRIPTION
**Pull request by Tatsujin1978**
- c++20 enabled
- minor refactoring

### CODE REVIEW

**Review by Maxnflaxl — CHANGES_REQUESTED** [review]
Please revert the translations commit.
The extra ```<byte value ="xd">``` should not be commited

**Comment by Tatsujin1978** [comment]
@Maxnflaxl , done.

**Comment by Tatsujin1978** [comment]
@Maxnflaxl , by the way, if these files is subject to change after recompilation then maybe would be better to add them into git ignore or something like this?

**Comment by Maxnflaxl** [comment]
> @Maxnflaxl , by the way, if these files is subject to change after recompilation then maybe would be better to add them into git ignore or something like this?

No, the translation files are necessary and updated by cmake.
We haven't found out yet why the ```<byte value="xd">``` is added in some cases.
@kogawulf experienced this too.

**Review by Maxnflaxl — APPROVED** [review]

**Comment by Tatsujin1978** [comment]
@Maxnflaxl , as I see it coused by lupdate: https://codereview.qt-project.org/c/qt/qttools/+/353347/25
So, maybe we have outdated tool.

image

**Comment by Maxnflaxl** [comment]
> @Maxnflaxl , as I see it coused by lupdate: https://codereview.qt-project.org/c/qt/qttools/+/353347/25 So, maybe we have an outdated tool.
> 
> image

@anatolse

 "On Windows, the line endings might be "\r\n",
depending on the source file. In .ts files this leads to an extra tag
<byte value="xd"/>. Fix this by converting Windows line endings to Unix
line endings when handling string literals."
(https://codereview.qt-project.org/c/qt/qttools/+/353347/25)

Seems not like we have an outdated tool, but incorrect line endings.

**Review by anatolse — APPROVED** [review]

**Pull request merged**
