### PR TITLE
Changed text 

### PR DESCRIPTION
**Pull request by SomethingGettingWrong**
https://github.com/BeamMW/beam-ui/issues/65

### CODE REVIEW

**Comment by echoby** [comment]
Source string with ID "logo-description" not provided for *.ts files

**Comment by SomethingGettingWrong** [comment]
There is more to it then what I did. I need to do the translation for each language in the *.ts. is what your asking correct? I did it for english.

**Comment by SomethingGettingWrong** [comment]
Alright I finished. Im going back to the other pull request. It only requested Native Language But ill go ahead and translate all of them.

**Comment by echoby** [comment]
> There is more to it then what I did. I need to do the translation for each language in the *.ts. is what your asking correct? I did it for english.

No you don't need to make translations, only 'source' tag update
`<source>your text</source>`
and english (en_US.ts) 'translation' tag update.

**Pull request merged**
